#!/bin/bash

# 
 # This file is part of the fr33zik distribution (https://github.com/fr33zik/servo_arm).
 # Copyright (c) 2019 Jaroslav Jablonicky.
 # 
 # This program is free software: you can redistribute it and/or modify  
 # it under the terms of the GNU General Public License as published by  
 # the Free Software Foundation, version 3.
 #
 # This program is distributed in the hope that it will be useful, but 
 # WITHOUT ANY WARRANTY; without even the implied warranty of 
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 # General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License 
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 #/

#for i in {10..20..5}
#do
#	gpio pwm 23 $i
#	sleep 3s
#done

#change to pwm
gpio mode 23 pwm
gpio pwm 0

#buttons
gpio mode 1 in
gpio mode 4 in
gpio mode 5 in
gpio mode 6 in

#select of demultiplexer
gpio mode 0 out
gpio mode 2 out
gpio mode 3 out

#set frequency
gpio pwmc 48
gpio pwmr 8000
gpio pwm-ms

#using s0 as empty
gpio write 0 0
gpio write 2 0
gpio write 3 0

servo="1"
hz=(600 600 600 600 600)
left="400"
right="800"
on=1
while true 
do

	inp1=$(gpio read 1)
	inp4=$(gpio read 4)
	inp5=$(gpio read 5)
	inp6=$(gpio read 6)
	#echo "$inp1 $inp4 $inp5 $inp6"
	
	#servo selector mode toggle
	if [ $inp1  -eq 1 ]; then
		on=$((1-on))
		echo control: $on
		if [ $on -eq 1 ];then
			gpio pwm 23 0
			gpio write 0 0
			gpio write 2 0
			gpio write 3 0
		else #select servo
	if [ $servo -eq "1" ]; then
		echo $servo
		gpio pwm 23 0
		gpio write 0 1
		gpio write 2 0
		gpio write 3 0
		gpio pwm 23 ${hz[servo]}
	elif [ $servo -eq "2" ]; then
		echo $servo
		gpio pwm 23 0
		gpio write 0 0
		gpio write 2 1
		gpio write 3 0
		gpio pwm 23 ${hz[servo]}
	elif [ $servo -eq "3" ]; then
		echo $servo
		gpio pwm 23 0
		gpio write 0 1
		gpio write 2 1
		gpio write 3 0
		gpio pwm 23 ${hz[servo]}
	elif [ $servo -eq "4" ]; then
		echo $servo
		gpio pwm 23 0
		gpio write 0 0
		gpio write 2 0
		gpio write 3 1
		gpio pwm 23 ${hz[servo]}
	elif [ $servo -eq "5" ]; then
		echo $servo
		gpio pwm 23 0
		gpio write 0 1
		gpio write 2 0
		gpio write 3 1
		gpio pwm 23 ${hz[servo]}
	elif [ $servo -eq "6" ]; then
		echo $servo
		gpio pwm 23 0
		gpio write 0 0
		gpio write 2 1
		gpio write 3 1
		gpio pwm 23 ${hz[servo]}
	elif [ $servo -eq "7" ]; then
		echo $servo
		gpio pwm 23 0
		gpio write 0 1
		gpio write 2 1
		gpio write 3 1
		gpio pwm 23 ${hz[servo]}

	fi
		
		fi
		sleep 1
	fi

#pwm control
if [ $on -eq 1 ];then
	if [ $inp4  -eq 1 ]; then
		echo " set 1"
			servo="1"
	elif [ $inp5  -eq 1 ]; then
		echo "servo -1"
		servo=$((servo - 1))
		if [ $servo -lt "1" ]; then
			servo="1"
		fi
	elif [ $inp6  -eq 1 ]; then
		echo "servo +1"
		servo=$((servo + 1))
		if [ $servo -gt "4" ]; then
			servo="4"
		fi
	fi
		echo $servo
		sleep 1
else
	if [ $inp4  -eq 1 ]; then
		echo "hard center"
		hz[$servo]="600"
	elif [ $inp5  -eq 1 ]; then
		echo "left steps ${hz[servo]}"
		hz[servo]=$((${hz[servo]} - 1))
		if [ ${hz[servo]} -lt "400" ]; then
			hz[servo]="400"
		fi
	elif [ $inp6  -eq 1 ]; then
		echo "right steps ${hz[servo]}"
		hz[servo]=$((${hz[servo]} + 1))
		if [ ${hz[servo]} -gt "800" ]; then
			hz[servo]="800"
		fi
	fi
		gpio pwm 23 ${hz[servo]}
		#echo ${hz[*]}
	fi


done
